export const AUTH_ROUTES = {
  SIGN_IN: '/auth/login',
  SIGN_UP: '/auth/register',
  GOOGLE_OAUTH_CALLBACK: '/google/oauth/callback',
  OAUTH_SUCCESS: '/auth/oauth/success',
  VERIFY_EMAIL: '/auth/verify-email',
  FORGET_PASSWORD: '/auth/forget-password',
  RESET_PASSWORD: '/auth/reset-password',
};

export const PROTECTED_ROUTES = {
  DASHBOARD: '/dashboard',
  DEALS_OFFER: '/dashboard/deal-offer',
  SETTINGS: '/dashboard/settings',
  SETTINGS_PROFILE: '/dashboard/settings/profile',
  SETTINGS_SECURITY: '/dashboard/settings/security',
  SETTINGS_ACTIVITY: '/dashboard/settings/activities',
  SETTINGS_PAYLUK_SETUPPAGE: '/dashboard/settings/payment-setup',
  NOTIFICATION: '/dashboard/notifications',
  BOOKMARK: '/dashboard/bookmarks',
  USER_PROFILE: '/dashboard/profile/user/:userId',
  BUSINESS_PROFILE: '/dashboard/profile/business/:userId',
  CREATE_PRODUCT: '/dashboard/post/create',
  MENU: '/dashboard/menu',
  CHAT: '/dashboard/chat',
  CART: '/dashboard/product/cart',
  CHECKOUT: '/dashboard/checkout',
  ORDER: '/dashboard/my-orders',
  CHAT_CONVERSATION: '/dashboard/chat/:conversationId',
  PRODUCT_DETAIL: '/dashboard/product/:productId',
  IMAGE_SEARCH: '/dashboard/search/image',
  STORE_MANAGEMENT: '/dashboard/store-management',
  WALLET: '/dashboard/wallet',
  WALLET_OVERVIEW: '/dashboard/wallet/overview',
};

export const BASE_ROUTE = {
  HOME: '/',
  ABOUT: '/about',
  CONTACT: '/contact',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  FAQ: '/faq',
  INVITE_URL: '/invite/workspace/:inviteCode/join',
  PAYLUK_PAYMENT_COMPLETE: '/payments/complete',
} as const;
